### ISSUE TITLE
vis_res.py error: no .pkl file

### ISSUE THREAD

**Issue by YYYYYHC** [rkjones4/ShapeCoder#1]
Hi,

I have set up the environment and tried to reproduce the visualization result with the result data you provide in this [link](https://drive.google.com/file/d/1CmuNsR06fRt0l-zTjnQ2m_HtUbIxa0n4/view?usp=sharing). However, after running the command of 
`python vis_res.py ../shapecoder_results/shapeCoder_res/chair/ 1 ../test_result/`

there is an error occurs:

![image](https://github.com/rkjones4/ShapeCoder/assets/56374152/1c63e375-b85f-460a-8efe-d02641642874)

I have checked the shapecoder_result/shapeCoder_res/chair-storage-table folders that the .pkl file doesn't exist. There is only end_data/lib.txt files

![image](https://github.com/rkjones4/ShapeCoder/assets/56374152/883b7266-bbb7-42d7-8248-72dbbcb7fdf9)

Hope to your feedback. Thank you again for the interesting work.

**Comment by rkjones4** [comment]
Hi, thanks for noticing this inconsistency! 

The visualization script was designed to be run on pkl files (i.e. new shapecoder runs), as some information (removed library functions and gt primitive layouts) are not saved in the end_data/end_lib text files. 

I've uploaded a fall-back option in the visualization script that tries to visualize the information form only the end_data/end_lib text files -- this should in most cases succeed (although it may fail in some cases, depending on the saved library structure), and will visualize the predicted programs, but not any of the GT layouts. 

If your goal is to visualize the results of those particular end_data/end_lib pairs, results of the script are provided in the shapecoder_results/shapeCoder_vis/ folder. 

Please let me know if this helps, thanks!
